
FSHOnly: false

  # ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
  # │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
  # │  used properties are included. For a list of all supported properties and their functions,     │
  # │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
  # ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: uk.nhs.england
canonical: https://fhir.nhs.uk/England
name: NHSEnglandInteroperability

title: Interoperability Standards - Discovery

# description: Example Implementation Guide for getting started with SUSHI
status: draft
version: 0.0.1
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
license: Apache-2.0
jurisdiction: urn:iso:std:iso:3166#GB-ENG "England"
publisher:
  name: NHS England
  url: https://www.england.nhs.uk/
  # email: test@example.org

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
dependencies:
  fhir.r4.ukcore.stu3.currentbuild:
    version: 0.0.6-pre-release
    uri: https://simplifier.net/guide/ukcoreversionhistory
  fhir.r4.nhsengland.stu1:
    uri: https://simplifier.net/guide/nhs-england-implementation-guide-version-history
    version: 1.1.0
  hl7.fhir.uv.sdc: 3.0.0
 # ihe.iti.pdqm: 2.4.0
 # hl7.fhir.eu.laboratory: 0.1.0-ballot

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Documentation:
    Background: background.html
    Interoperability Standards: interoperability-standards.html
    Conformance and Testing (FHIR): testing.html
  Design:
    Administration : administration-module.html
    Documents (Clinical): documents-module.html
    Clinical: clinical-module.html
    Diagnostics: diagnostics-module.html
    Medications: medications-module.html
    Workflow: workflow.html
    Structured Data Capture: structured-data-capture.html
    FHIR Validation: validation.html
  Build:
    National Proxy Service: national-proxy-service.html
    Personal Demographics Service: personal-demographics-service.html
    Multicast Notification Service: multicast-notification-service.html
  FHIR Assets: artifacts.html
  Support:
    Downloads: downloads.html

